on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Semantic Release
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 25
      - run: npm ci
      - run: npm audit signatures
      # - name: Configure git identity
      #   run: |
      #     git config user.name "github-actions[bot]"
      #     git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # In case you want to publish to Visual Studio Marketplace
          VSCE_PAT: ${{ secrets.VS_MARKETPLACE_TOKEN }}
          # In case you want to publish to Open VSX Registry
          # OVSX_PAT: ${{ secrets.OVSX_PAT }}
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npm run release
      # - name: Publish to Open VSX Registry
      #   uses: HaaLeo/publish-vscode-extension@v2
      #   with:
      #     pat: ${{ secrets.OPEN_VSX_TOKEN }}
      # - name: Publish to Visual Studio Marketplace
      #   uses: HaaLeo/publish-vscode-extension@v2
      #   with:
      #     pat: ${{ secrets.VS_MARKETPLACE_TOKEN }}
      #     registryUrl: https://marketplace.visualstudio.com
